name: SmashHit
version: "1.0-RC2"
author: "frash23"
main: "com.frash23.smashhit.SmashHit"
depend: [ ProtocolLib ]
softdepend: [ WorldGuard ]
commands:
  smashhit:
    aliases: [ sh ]
    permission: smashhit.admin